Repository jumpserver/luna, pull requests merged in 2020-07, with the labels that each got.

#197 ci(pull-request): 添加自动pr打标签功能
  .github/workflows/pr-auto-labels.yml
Labels: 无需处理

#198 fix(cookie): 添加Cookie时间
  src/app/elements/nav/nav.component.ts
  src/app/services/app.ts
Labels: fix

#204 ci(github): 添加JumpServer仓库通用的action
  .github/workflows/jms-generic-action-handler.yml
Labels: 无需处理

#207 ci(github): 添加JumpServer仓库通用的action
  .github/workflows/jms-generic-action-handler.yml
Labels: 无需处理

#206 ci(github): 添加JumpServer仓库通用的action
  .github/workflows/jms-generic-action-handler.yml
Labels: 无需处理

#205 ci(github): 添加JumpServer仓库通用的action
  .github/workflows/jms-generic-action-handler.yml
Labels: 无需处理

#211 fix(Splitter): 修复拖动按钮没有正常显示的问题
  src/app/pages/main/main.component.ts
Labels: fix

#203 fix: 修复Luna资产树搜索异常
  src/app/elements/asset-tree/asset-tree.component.ts
Labels: fix

#200 feat: Luna支持从Core中获取favicon
  src/app/services/setting.ts
Labels: 新功能
